export default [
  {
    engine: '2-stroke',
    capacity: 125,
    maxPower: 35,
    torque: 28,
    cylinderCount: 1,
    bore: 55,
    stroke: 65,
    weight: 120,
    topSpeed: 110,
    transmission: '6 gears, MT',
    compressionRatio: 'xxx',
    suspension: 'Sanchez',
    frame: 'Alloy',
    wheelbase: 1597,
    rakeTrail: 'wtf',
    wheelSizes: '21" F, 19" R',
    tires: 'Excel',
    brakes: 'Brembo',
    seatHeight: 992,
    fuelCapacity: 7.5,
    ignitionType: 'Kickstarr',
    kickstand: false,
    lights: 'none',
    storageSpace: false,
  },
];
