export default [
  {
    year: 2012,
    type: 'motocross',
    maxPeople: 1,
    roadLegal: false,
    licenseRequired: 'not required',
    minRentalPeriod: 1,
    maxRentalPeriod: 14,
    termsOfUse: 'http://url.to.terms.of.use',
  },
  {
    year: 2012,
    type: 'motocross',
    maxPeople: 1,
    roadLegal: false,
    licenseRequired: 'not required',
    minRentalPeriod: 1,
    maxRentalPeriod: 14,
    termsOfUse: 'http://url.to.terms.of.use',
  },
  {
    year: 2012,
    type: 'motocross',
    maxPeople: 1,
    roadLegal: false,
    licenseRequired: 'not required',
    minRentalPeriod: 1,
    maxRentalPeriod: 14,
    termsOfUse: 'http://url.to.terms.of.use',
  },
];
